version: "3.9"
services:
  web:
    image: golang:1.17.0
    build: .
    container_name: todos-server
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: >
          go run -mod=vendor main.go -b 0.0.0.0
    restart: unless-stopped

  cache:
    container_name: "redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"
    # environment:
    #   - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --bind redis --requirepass ${REDIS_PASS} --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    volumes:
      - cache:/data

  db:
    image: postgres:alpine
    container_name: todos-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - postgres-db:/var/lib/postgresql/data
      
volumes:
  cache:
    driver: local
  postgres-db: